# -*- coding: utf-8 -*-

from re import search

# Common errors generated by OCR, and other stuffs to remove
ocr_common_errors = {
    "?":"", "!":"", "|":"", ":":"",
    "\n":" ", "‘":" ", "î":"i", "ì":"i",
    "ﬁ":"fi", "perla":"per la", "ii":"il",
    " ia ": " la ", "“":"li", "|i":"il",
    "ò":"o", "\x0c":'', "diun":"di un",
    "sapen":"saper", "|n":"in", "Ii":"li",

    "\"":'', "-":'' # quote and dash are google search parameters and can skew the results
}

# Words to remove from question text
not_allowed_words = [
    "qual", "quale", "cosa", "chi", "che", "quando", "il", "lo", "la", "i", "gli", "le", "l",
    "di", "a", "da", "in", "con", "su", "per", "tra", "fra", "del", "dello", "della", "degli",
    "dei", "delle", "dell", "un", "uno", "una", "è", "é", "questo", "questa", "questi", "queste",
    "mio", "mia", "miei", "mie", "tuo", "tua", "tuoi", "tue", "suo", "sua", "suoi", "sue",
    "nostro", "nostra", "nostri", "nostre", "vostro", "vostra", "vostri", "vostre", "loro",
    "nel", "nello", "nella", "negli", "nelle", "nell", "mai"
]

# Words to remove from answers text
not_allowed_words_in_answers = [
    "il", "lo", "la", "i", "gli", "le", "l", "un", "uno", "una"
]


def clean_question(question):
    text = question.get_text()
    
    # Remove common OCR errors
    for find, replace in ocr_common_errors.items():
        text = text.replace(find, replace)

    # Replace words to create a shorter text
    text = text.replace("come si chiama", "nome")
    
    # If question contain a '?' after some numbers, like a date,
    # OCR recognize it as '7' (seven), therefore it must be removed
    # Regexp reminder: \d=any digit numbers; {4} how many digit numbers
    four_digit_match = search("\d{4}7", text)
    if four_digit_match:
        # Span is a tuple (x,y) that contain initial-final index of matched substring
        span = four_digit_match.span()
        text = text[:span[0]] + str(text[span[0]:span[1]].replace('7','')) + text[span[1]:]
    
    # If question contain a 'è' or 'é' preceded by ' ' (a space) 
    # and followed by another char, then insert ' ' between 'è' and the char
    accent_match = search("\s(é|è)[a-zA-Zèé]+", text)
    if accent_match:
        span = accent_match.span()
        text = text[:span[0] + 2] + ' ' + text[span[0] + 2:]
    
    # Split question in a list, for each word
    words = text.split(' ')
    
    # Reminder: syntax like `list[:]` mean that Python create a copy of the original list
    # to prevent index shifting when an item is removed from the list on which the for is iterating
    for word in words[:]:
        if word in not_allowed_words:
            words.remove(word)
    
    # Rebuild text as a string 
    text = ' '.join(words)
    
    # Set the new, cleaned text into question object 
    question.set_cleaned_text(text)


def clean_answer(answer):
    if answer == '': return "OCR Failed"
    
    # Remove common OCR errors
    for find, replace in ocr_common_errors.items():
        answer = answer.replace(find, replace)

    # Split question in a list, for each word
    words = answer.split(' ')
    
    # Reminder: syntax like `list[:]` mean that Python create a copy of the original list
    # to prevent index shifting when an item is removed from the list on which the for is iterating
    for word in words[:]:
        if word in not_allowed_words_in_answers:
            words.remove(word)
    
    # Rebuild text as a string 
    answer = ' '.join(words)
    
    return answer
